#!/bin/bash
#
# (C) 2018 Stefan Schallenberg
# 
# Root wrapper
# correct ownership of files and call
# finance-entrypoint as restricted user.

printf "Setting permissions of /finance\n"
# change all files ownership to finance:finance
# use find instead of chown -R avoids touching all files. This is especially
# useful for backups
find /finance -! -user finance -exec chown finance {} ";"
find /finance -! -group finance -exec chown :finance {} ";"

# set permission to rr- of /finance/.hbci-pinfile
find /finance -name .hbci-pinfile -maxdepth 1 -perm /o=rwx -exec chmod o-rwx {} ";"
find /finance -name .hbci-pinfile -maxdepth 1 -perm /g=wx -exec chmod g-wx {} ";"
find /finance -name .hbci-pinfile -maxdepth 1 -perm /u=wx -exec chmod u-wx {} ";"

printf "Switching to restricted user finance\n"
cd /finance
su finance -c /usr/local/bin/finance-entrypoint