---
# Don't report passed checks in output
quiet: true
skip-check:
  - CKV_DOCKER_2
    # HEALTHCHECK not mandatory in our environment
  - CKV_K8S_10
    # CPU requests not mandatory in our environment
  - CKV_K8S_11
    # CPU limits not mandatory in our environment
  - CKV_K8S_12
    # Memory requests not mandatory in our environment
  - CKV_K8S_13
    # Memory limits not mandatory in our environment
  - CKV_K8S_15
    # ImagePullPolicy != Always accepted to avoid docker hub rate limiting
  - CKV_K8S_43
    # ImageDigest is not needed, version tag is enough
